### ISSUE TITLE
Channel movement is still bugged

### ISSUE THREAD

**Issue by azwong42** [Moonrise55/Mbot#36]
Solving puzzles drops them 2 spaces below the most recent green checkmark. Presumably this is either an issue with `channel.move()` or the way we're counting category channels.

**Comment by TheOriginalSoni** [comment]
I am "pretty" sure I've seen this problem in Bot-Be-Named before, I just cant remember the exact cause. I recommend just printing a list of channels and their positions. That's what explained the weirdness.

It was some combination of "Voice channels and/or categories themselves occupy positions" and "0 based indexing was really 1 based indexing" IIRC.
